import 'package:flutter/foundation.dart';

class LocalizationService {
  LocalizationService._private();

  static final LocalizationService instance = LocalizationService._private();

  final ValueNotifier<String> language = ValueNotifier<String>('en');

  static const supported = ['en', 'roman'];

  final Map<String, Map<String, String>> _t = {
    'en': {
      'title': 'Yahya&Co',
      'enter_email': 'Please enter your email address',
      'email_hint': 'Email Address',
      'invalid_email': 'Please enter a valid email address',
      'email_verification':
          'Check your inbox folder for the verification email.',
      'verify_email': 'Verify Email',
        'sign_in': 'Sign In',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'create_account': 'Create Account',
        'have_account': 'Already have an account?',
        'dont_have_account': 'Need an account?',
        'forgot_password': 'Forgot Password?',
        'reset_password': 'Reset Your Password',
        'password_reset_title': 'Password reset successfully',
        'password_reset_description': "Enter your email address and we'll send you a link to reset your password.",
        'password_reset_sent': 'Please check your inbox and spam folder for the password reset link.',
        'email_address': 'Email Address',
        'send_reset_link': 'Send Reset Link',
        'password_reset_error': 'Unable to send password reset email',
        'resend_verification': 'Resend Verification Email',
        'invalid_password': 'Password must be at least 6 characters',
        'passwords_dont_match': 'Passwords do not match',
        'email_not_verified': 'Please verify your email first',
          'invalid_pin': 'Invalid PIN',
          'cash_account_required': 'Please add a Cash account first',
      'verification_sent':
          'Email verification link sent. Please check your inbox or spam folder.',
      'verifying_email': 'Verifying your email...',
      'verification_error': 'Error sending verification email',
      'otp_title': 'Enter the 6-digit Code',
      'otp_hint': 'Verification Code',
      'invalid_code': 'Please enter the 6-digit verification code',
      'verify_code': 'Verify Code',
      'enter_phone': 'Please enter your phone number',
      'phone_hint': 'Phone Number',
      'send_otp': 'Send OTP',
      'ready_otp': 'Ready to get OTP?',
      'invalid_phone': 'Please enter a valid 10-digit mobile number',
      'didnt_get_code': "Didn't get the code?",
      'resend_otp': 'Resend OTP',
      'verifying': 'Verifying...',
      'select_language': 'Language',
      'english': 'English',
      'roman': 'Roman Urdu',
      'english_short': 'EN',
      'roman_short': 'UR',
      'phone_verified': 'Phone Verified!',
      'account_ready': 'Your account is ready',
      'business_details': 'Business Details',
      'enter_business_info': 'Enter the business name and type',
      'business_name': 'Business Name',
      'business_type': 'Business Type',
      'select_type': 'Select a business type',
      'next': 'Next',
      'retail': 'Retail',
      'service': 'Service',
      'manufacturing': 'Manufacturing',
      'wholesale': 'Wholesale',
      'distribution': 'Distribution',
      'import_export': 'Import/Export',
      'other': 'Other',
      'please_enter_business_name': 'Please enter a business name',
      'please_select_business_type': 'Please select a business type',
      'business_created_success': 'Business created successfully!',
      'set_pin': 'Set PIN',
      'secure_your_account': 'Secure your account with a PIN',
      'enter_pin': 'Enter 4-digit PIN',
      'confirm_pin': 'Confirm 4-digit PIN',
      'pin_hint': 'Enter PIN',
      'confirm_pin_hint': 'Confirm PIN',
      'pins_dont_match': 'PINs do not match',
      'pin_too_short': 'PIN must be 4 digits',
      'please_enter_pin': 'Please enter a PIN',
      'pin_set_success': 'PIN set successfully!',
      'sign_up': 'SignUp',
      'skip': 'Skip',
      'enter_pin_to_login': 'Remember this pin to login app everytime',
      'verify': 'Verify',
      'forgot_pin': 'Forgot Pin?',
      'forgot_pin_contact_support': 'Please contact support to reset your PIN',
      'pin_verified_success': 'PIN verified successfully!',
    },
    'roman': {
      'title': 'Yahya&Co',
      'enter_email': 'Baraye mehrbani apna email address darj karen',
      'email_hint': 'Email Address',
      'invalid_email': 'Baraye mehrbani sahih email address darj karen',
      'email_verification':
          'Verification email dekhne ke liye apna inbox folder check karen.',
      'verify_email': 'Email verify karen',
        'sign_in': 'Sign In',
        'password': 'Password',
        'confirm_password': 'Confirm Password',
        'create_account': 'Account Banain',
        'have_account': 'Kya pehle se account hai?',
        'dont_have_account': 'Naya account banana hai?',
        'forgot_password': 'Password bhool gaye?',
        'reset_password': 'Apna password reset karen',
        'password_reset_title': 'Password reset kamyabi se ho gaya hai',
        'password_reset_description': 'Apna email address darj karen aur hum aapko password reset karne ka link bhejenge.',
        'password_reset_sent': 'Password reset link ke liye apna inbox aur spam folder check karen.',
        'email_address': 'Email Address',
        'send_reset_link': 'Reset Link Bhejain',
        'password_reset_error': 'Password reset email bhejne mein masla hua',
        'resend_verification': 'Verification email dobara bhejen',
        'invalid_password': 'Password kam az kam 6 characters ka hona chahiye',
        'passwords_dont_match': 'Passwords match nahi karte',
        'email_not_verified': 'Baraye mehrbani pehle email verify karen',
          'invalid_pin': 'Ghalat PIN',
          'cash_account_required': 'Baraye mehrbani pehle Cash account banain',
      'verification_sent':
          'Verification email bhej di gayi hai. Apna inbox ya spam folder check karen.',
      'verifying_email': 'Aapki email verify ho rahi hai...',
      'verification_error': 'Verification email bhejne mein error',
      'otp_title': '6-digit code darj karen',
      'otp_hint': 'Verification Code',
      'invalid_code': 'Baraye mehrbani 6-digit verification code darj karen',
      'verify_code': 'Code verify karen',
      'enter_phone': 'Aapna phone number darj karen',
      'phone_hint': 'Phone Number',
      'send_otp': 'OTP Bhejain',
      'ready_otp': 'OTP lenay ke liye tayyar hain?',
      'invalid_phone':
          'Baraye mehrbani sahih 10 digit wala mobile number darj karen',
      'didnt_get_code': 'Code nahi mila?',
      'resend_otp': 'OTP dobara bhejen',
      'verifying': 'Verify ho raha hai...',
      'select_language': 'Zuban',
      'english': 'English',
      'roman': 'Roman Urdu',
      'english_short': 'EN',
      'roman_short': 'UR',
      'phone_verified': 'Phone Verified!',
      'account_ready': 'Aapka account tayyar ho gya',
      'business_details': 'Karobaar Ki Tafseelaat',
      'enter_business_info': 'Karobaar ka naam aur qism darj karen',
      'business_name': 'Karobaar Ka Naam',
      'business_type': 'Karobaar Ki Qism',
      'select_type': 'Karobaar ki qism select karen',
      'next': 'Agle Qdam',
      'retail': 'Chhoti Dukaan',
      'service': 'Khidmat',
      'manufacturing': 'Tayyari',
      'wholesale': 'Thok Farosh',
      'distribution': 'Takseem',
      'import_export': 'Daraamad/Baramad',
      'other': 'Kuch Aur',
      'please_enter_business_name':
          'Baraye mehrbani karobaar ka naam darj karen',
      'please_select_business_type':
          'Baraye mehrbani karobaar ki qism select karen',
      'business_created_success': 'Karobaar kamyabi se bana diya gya!',
      'set_pin': 'PIN Banain',
      'secure_your_account': 'Apne account ko PIN se mehfooz banain',
      'enter_pin': '4-digit PIN darj karen',
      'confirm_pin': '4-digit PIN dobara darj karen',
      'pin_hint': 'PIN darj karen',
      'confirm_pin_hint': 'PIN dobara darj karen',
      'pins_dont_match': 'PIN barabari nahi rakhte',
      'pin_too_short': 'PIN 4 digits ka hona chahiye',
      'please_enter_pin': 'Baraye mehrbani PIN darj karen',
      'pin_set_success': 'PIN kamyabi se set ho gya!',
      'sign_up': 'SignUp',
      'skip': 'Chhod Den',
      'enter_pin_to_login': 'Is pin ko har baar app login karte waqt yaad rakhein',
      'verify': 'Verify Karen',
      'forgot_pin': 'PIN bhool gaye?',
      'forgot_pin_contact_support': 'Aapka PIN reset karne ke liye support se rabta karen',
      'pin_verified_success': 'PIN kamyabi se verify ho gya!',
    },
  };

  String t(String key) {
    final lang = language.value;
    return _t[lang]?[key] ?? key;
  }

  void setLanguage(String lang) {
    if (!supported.contains(lang)) return;
    language.value = lang;
  }
}
