// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGk9KZ-7IGlRUvyoenrcWSQSYRMv8sBx0',
    appId: '1:396051505153:web:f27a683ba98dc7dbe02000',
    messagingSenderId: '396051505153',
    projectId: 'yahyaandco-5de39',
    authDomain: 'yahyaandco-5de39.firebaseapp.com',
    storageBucket: 'yahyaandco-5de39.firebasestorage.app',
    measurementId: 'G-DSX3GT4XH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qHKP8NvXzQO0Ynr42_t5SNCzEct6_yY',
    appId: '1:396051505153:android:a5262b7ec1affb65e02000',
    messagingSenderId: '396051505153',
    projectId: 'yahyaandco-5de39',
    storageBucket: 'yahyaandco-5de39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHSaf4ROX8EAQLzv_09x2aM6NGHCjSmpM',
    appId: '1:396051505153:ios:0f28a7c1a3faa421e02000',
    messagingSenderId: '396051505153',
    projectId: 'yahyaandco-5de39',
    storageBucket: 'yahyaandco-5de39.firebasestorage.app',
    iosBundleId: 'com.example.yahyaAndCo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHSaf4ROX8EAQLzv_09x2aM6NGHCjSmpM',
    appId: '1:396051505153:ios:0f28a7c1a3faa421e02000',
    messagingSenderId: '396051505153',
    projectId: 'yahyaandco-5de39',
    storageBucket: 'yahyaandco-5de39.firebasestorage.app',
    iosBundleId: 'com.example.yahyaAndCo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGk9KZ-7IGlRUvyoenrcWSQSYRMv8sBx0',
    appId: '1:396051505153:web:c0ca1a06c086d492e02000',
    messagingSenderId: '396051505153',
    projectId: 'yahyaandco-5de39',
    authDomain: 'yahyaandco-5de39.firebaseapp.com',
    storageBucket: 'yahyaandco-5de39.firebasestorage.app',
    measurementId: 'G-YCWCQV9FC5',
  );
}
